config/routes.rb
# encoding: UTF-8
Rails.application.routes.draw do
  devise_scope :usuario do
    get 'sign_out' => 'sessions#destroy'
    get 'usuarios/sign_in' => 'sessions#new'
    get 'usuarios/sign_up' => 'registrations#new'

    # El siguiente para superar mala generación del action en el formulario
    # cuando se autentica mal (genera 
    # /puntomontaje/puntomontaje/usuarios/sign_in )
    if (Rails.configuration.relative_url_root != '/') 
      ruta = File.join(Rails.configuration.relative_url_root, 
                       'usuarios/sign_in')
      post ruta, to: 'devise/sessions#create'
    end
    root 'sessions#new'
  end
  devise_for :usuarios, module: :devise, controllers: { registrations: "registrations" }
  as :usuario do
          get 'usuarios/edit' => 'devise/registrations#edit', 
            :as => 'editar_registro_usuario'    
          put 'usuarios/:id' => 'devise/registrations#update', 
            :as => 'registro_usuario'           
  end
  resources :usuarios, path_names: { new: 'nuevo', edit: 'edita' } 
  post 'usuarios/crea' => 'usuarios#create', :as => 'crea_usuario'           
  patch 'usuarios/:id/actualiza' => 'usuarios#update', :as => 'actualiza_usuario'           
  get 'usuarios/reconfirma' => 'usuarios#reconfirma'
  get 'bitacora/admin' => 'sal7711_gen/bitacora#admin', as: 'bitacora_admin'
  get 'bitacora/tiempo' => 'sal7711_gen/bitacora#tiempo', as: 'bitacora_tiempo'

  get 'sincroniza' => 'sal7711_gen/buscar#sincroniza', as: 'buscar_sincroniza'

#	get 'buscar/:id', to: 'buscar#mostraruno'
#	get 'buscar' => 'buscar#index'
# get 'mundep' => 'buscar#mundep'
# get 'codigo' => 'admin/categoriaprensa#busca'

  resource "contacto", only: [:new, :create]

  mount Sal7711Gen::Engine => "/", as: 'sal7711_gen'
  mount Sip::Engine => "/", as: 'sip'

  namespace :admin do
    Ability.tablasbasicas.each do |t|
      #puts "OJO config/routes.rb, t=" + t.to_s
      if (t[0] == "") 
        c = t[1].pluralize
        resources c.to_sym, 
          path_names: { new: 'nueva', edit: 'edita' }
      end
    end
  end


end

app/views/layouts/application.html.erb
<% content_for :titulo do %>
  Archivo Digital de Prensa
<% end %>

<% content_for :marca do %>
  <img class='logo-cinep' src="/images/logo.png">
  Archivo Digital de Prensa
<% end %>

<% content_for :menu do %>
  <%= menu_group do %>
    <% if current_usuario %>
      <%= menu_item "Buscar", "/buscar" %>
      <%= menu_item "Manual de Uso", "/Manual_de_Uso_Archivo_Digital_de_Prensa_CINEP.pdf", target: '_blank' %>
      <%= menu_item "Acerca de", sip.acercade_path %>
    <% end %>
  <% end %>
  <%= menu_group :pull => :right do %>

    <% urlop = Rails.configuration.action_mailer.default_url_options %>
    <% if current_usuario %>
      <% if !current_usuario.autenticado_por_ip %>
        <%= drop_down "Administrar" do %>
          <%= menu_item "Clave", main_app.editar_registro_usuario_path %>
          <% if current_usuario.rol == Ability::ROLADMIN %>
            <%= menu_item "Usuarios", main_app.usuarios_path %>
            <%= menu_item "Tablas Básicas", sip.tablasbasicas_path %>
            <%= menu_item "Consultas por usuario", "/bitacora/admin" %>
            <%= menu_item "Consultas en tiempo", "/bitacora/tiempo" %>
            <%= menu_item "Enviar instrucciones de reconfirmación", "/usuarios/reconfirma" %>
          <% end %>
        <% end %>
        <%= menu_item "Salir #{current_usuario.nusuario}", main_app.sign_out_path %>
      <% else %>
        <%= menu_item "Ingresar", 
          Rails.application.routes.url_helpers.new_usuario_session_url( urlop )
        %> 
        <%= menu_item "Inscribirse", 
          Rails.application.routes.url_helpers.new_usuario_registration_url(urlop)
        %>
        <% puts "current_usuario es ", current_usuario.inspect %>
        <% org = ::Organizacion.where('usuarioip_id = ?', current_usuario.id).take
           url = org ? org.url_logoinst : nil  %>
        <% if url %>
          <li><img class='logo-inst' src="<%= url %>"></span></li>
        <% end %>
      <% end %>
    <% else %>
      <%= menu_item "Ingresar", 
          Rails.application.routes.url_helpers.new_usuario_session_url( urlop, only_path: true )
      %> 
      <%= menu_item "Inscribirse", 
        Rails.application.routes.url_helpers.new_usuario_registration_url(urlop, only_path: true)
      %>
    <% end %>
  <% end %>
<% end %>

<% content_for :piedepagina do %>
  <div class="pie">
    <p> Contenidos con derechos reservados. Pueden ser utilizado total o 
    parcialmente, siempre y cuando se cite como fuente al <a href="http://www.cinep.org.co">CINEP/Programa 
      por la Paz</a>.</p>
    <p>Teléfono: (57)(1) 245.6181  /  Fax: (57)(1) 287.9089  /  Email: <a href="mailto:cinep@cinep.org.co">cinep@cinep.org.co</a>  /  Dirección: Cra 5 No. 33B- 02 Bogotá, Colombia.</p>
    <p>Sistema de información desarrollado por 
      <a href="http://www.pasosdeJesus.org">Pasos de Jesús</a>
    </p>
  </div>
<% end %>

<%= render template: "layouts/sal7711_gen/application" %>